# Generated by Django 4.2.11 on 2026-05-13 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('event_name', models.CharField(db_index=True, max_length=255)),
                ('source', models.CharField(choices=[('api', 'API'), ('csv', 'CSV Upload'), ('webhook', 'Webhook')], default='api', max_length=20)),
                ('properties', models.JSONField(default=dict)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizations.organization')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organization', 'timestamp'], name='events_organiz_e1d8c3_idx'), models.Index(fields=['organization', 'event_name', 'timestamp'], name='events_organiz_cb0edd_idx'), models.Index(fields=['organization', 'event_type', 'timestamp'], name='events_organiz_e936ff_idx'), models.Index(fields=['is_processed', 'ingested_at'], name='events_is_proc_3bc196_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('key_prefix', models.CharField(max_length=10)),
                ('key_hash', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='organizations.organization')),
            ],
            options={
                'db_table': 'api_keys',
                'indexes': [models.Index(fields=['key_prefix'], name='api_keys_key_pre_9c2634_idx'), models.Index(fields=['organization', 'is_active'], name='api_keys_organiz_70e45b_idx')],
            },
        ),
    ]
