# Generated by Django 4.2.11 on 2026-05-13 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('metric', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('gt', 'Greater than'), ('lt', 'Less than'), ('eq', 'Equals')], max_length=10)),
                ('threshold', models.FloatField()),
                ('window_minutes', models.IntegerField(default=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('triggered', 'Triggered'), ('resolved', 'Resolved'), ('muted', 'Muted')], default='active', max_length=20)),
                ('notification_channels', models.JSONField(default=list)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='organizations.organization')),
            ],
            options={
                'db_table': 'alert_rules',
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggered_value', models.FloatField()),
                ('threshold', models.FloatField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('alert_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='alerts.alertrule')),
            ],
            options={
                'db_table': 'alert_history',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
